document.addEventListener("DOMContentLoaded", function() {
    const books = [
        { "synopsis" : "500 Fantastic Facts - \"500 Fantastic Facts\" is a book filled with intriguing and surprising facts on topics like history, science, animals, and space. It presents information in a fun and engaging way, making learning enjoyable for readers of all ages. Each fact is designed to be easy to understand, with colorful illustrations enhancing the experience. The book encourages curiosity by providing a wide variety of fascinating tidbits. Whether for casual reading or educational purposes, it offers an exciting way to discover new knowledge."  ,"id" : "0" , "return_date": "2025-03-14", "title": "500 Fantastic Facts", "author": "Dan Green", "image": "500 fantastic facts- non fiction.jpg", "category": "non-fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Unavailable"},
        { "synopsis" : "A Map of Days (The Fourth Novel of Miss Peregrine's Peculiar Children) - \"A Map of Days\" is the fourth novel in the Miss Peregrine's Home for Peculiar Children series by Ransom Riggs, published in 2018. The story follows Jacob Portman as he returns to America with Miss Peregrine and his peculiar friends, exploring a hidden world of peculiars in the United States. Unlike in England, the American peculiar society is dangerous and unregulated, forcing Jacob to take on new responsibilities. He embarks on a journey to uncover secrets left behind by his grandfather, Abe, leading him deeper into the peculiar underground. Along the way, Jacob and his friends face unexpected challenges and threats that test their courage and friendships. The novel blends fantasy, historical fiction, and eerie vintage photography, continuing the mysterious and thrilling adventure of the peculiar children." ,"id" : "1" , "return_date": "", "title": "A Map of Days (The Fourth Novel of Miss Peregrine's Peculiar Children)", "author": "Ransom Riggs", "image": "a map of days- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "Diary of a Wimpy Kid The Meltdown - \"Diary of a Wimpy Kid: The Meltdown\" is the 13th book in Jeff Kinney's bestselling series, published in 2018. The story follows Greg Heffley as his town experiences a massive snowstorm, turning his neighborhood into a snowy battlefield. With school canceled, kids divide into rival groups, waging epic snowball fights and building elaborate snow forts. Greg and his best friend Rowley Jefferson struggle to defend their territory while dealing with bullies and chaotic neighborhood warfare. As tensions rise, the battle intensifies, leading to hilarious and unexpected challenges. Greg tries to stay out of trouble but inevitably gets caught in the middle of the madness. The book humorously explores childhood friendships, rivalries, and the fun (and frustration) of a snow day." ,"id" : "2" , "return_date": "2025-03-21", "title": "Diary of a Wimpy Kid The Meltdown", "author": "Jeff Kinney", "image": "diary of a wimpy kid the meltdown- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Unavailable"},
        { "synopsis" : "Fantastic Beasts: The Crimes of Grindelwald 2 - \"Fantastic Beasts: The Crimes of Grindelwald\" is the second film in the Fantastic Beasts series, released in 2018 and set in J.K. Rowling's Wizarding World. The story follows Newt Scamander, who is recruited by Albus Dumbledore to help stop the dark wizard Gellert Grindelwald, who has escaped custody and is gathering followers for his cause. Grindelwald seeks to create a world ruled by pure-blood wizards, manipulating the powerful and troubled Credence Barebone to discover his true heritage. As Newt and his allies travel across Paris, they encounter old friends like Tina Goldstein and Queenie, who is drawn to Grindelwald's promises. A shocking revelation unfolds as Credence's identity is exposed, altering the course of wizarding history. The film ends with Grindelwald gaining more power, setting the stage for a greater conflict between good and evil." ,"id" : "3" , "return_date": "", "title": "Fantastic Beasts: The Crimes of Grindelwald 2", "author": "J.K. Rowling", "image": "fantastic beast- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "Guinness World Records - The Guinness World Records 2019 edition, published in 2018, features an exciting collection of record-breaking feats, incredible human achievements, and fascinating facts from around the world. This edition highlights space exploration, cutting-edge technology, extreme sports, and mind-blowing stunts. A special section focuses on \"Maker Culture,\" showcasing innovators, inventors, and DIY enthusiasts who push the boundaries of creativity. It also includes the world's tallest and shortest people, fastest vehicles, strongest athletes, and bizarre talents. Stunning photography and behind-the-scenes stories provide readers with deeper insights into the challenges of breaking records. The book encourages people of all ages to set and break their own records while celebrating human potential and the wonders of the world." ,"id" : "4" , "return_date": "2025-03-16", "title": "Guinness World Records", "author": "Guinness World Records", "image": "guinness world records 2019- non fiction.jpg", "category": "non-fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2019", "status": "Unavailable"},
        { "synopsis" : "I Can't Believe It! 2 - \"I Can't Believe It! 2\" is a fascinating book filled with mind-blowing facts, stunning photographs, and incredible illustrations. It covers a wide range of topics, including space, dinosaurs, food, and unusual natural phenomena. The book presents unbelievable but true information, making learning fun and exciting for readers of all ages. It combines content from bestselling DK books, ensuring a rich collection of strange and amazing facts. Perfect for curious minds, this book is designed to surprise, educate, and entertain." ,"id" : "5" , "return_date": "", "title": "I Can't Believe It! 2", "author": "D.K.", "image": "i cant believe it 2- non fiction.jpg", "category": "non-fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "Love Looks Pretty on You - \"Love Looks Pretty on You\" is a poetry and prose collection by Lang Leav, published in 2019. This book explores themes of love, self-discovery, empowerment, heartbreak, and healing through deeply personal and relatable pieces. Leav's writing touches on the complexities of relationships, the strength of women, and the journey of finding one's self-worth. With her signature lyrical and emotional style, she provides inspiration and comfort to readers experiencing love and loss. The book also highlights growth, resilience, and the beauty of self-love. \"Love Looks Pretty on You\" is perfect for fans of contemporary poetry and those looking for words that resonate with the heart." ,"id" : "6" , "return_date": "2025-03-30", "title": "Love Looks Pretty on You", "author": "Lang Leav", "image": "love looks pretty on you-fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2019", "status": "Unavailable"},
        { "synopsis" : "Pope Francis God is Young - \"God is Young\" is a book by Pope Francis, published in 2018, in which he shares his thoughts on youth, faith, and the future of the world. Through a heartfelt conversation, Pope Francis emphasizes the importance of young people in shaping society and encourages them to be active participants in building a better future. He addresses challenges faced by the youth, such as unemployment, inequality, and the struggle for identity, while urging the older generations to listen, support, and empower them. The book highlights the wisdom, energy, and creativity that young people bring, showing how their voices are essential in the Church and the world. Pope Francis also speaks about hope, compassion, and the role of faith in overcoming modern struggles. \"God is Young\" is an inspiring message that calls for intergenerational dialogue and a renewed focus on love, justice, and spiritual growth." ,"id" : "7" , "return_date": "", "title": "Pope Francis God is Young", "author": "Pope Francis and Thomas Leoncini", "image": "pope francis god is young- non fiction.jpg", "category": "non-fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "Queen of Air Darkness (The Dark Artifices) Book Three - \"Queen of Air and Darkness\" is the third and final book in The Dark Artifices series by Cassandra Clare, published in 2018. Following the tragic death of Livvy Blackthorn, the Shadowhunter world is thrown into chaos as the Cohort, a radical faction, gains power and threatens to divide the Clave. Emma Carstairs and Julian Blackthorn, struggling with their forbidden parabatai love, embark on a dangerous journey to the Unseelie Court in search of a way to stop the growing darkness. Meanwhile, Mark, Cristina, and Kieran navigate faerie politics, and Ty Blackthorn is determined to bring Livvy back, risking dangerous magic. As war looms and dark forces rise, Emma and Julian must make heartbreaking choices to protect their loved ones. The novel delivers an epic conclusion filled with love, sacrifice, betrayal, and redemption, shaping the future of the Shadowhunter world." ,"id" : "8" , "return_date": "", "title": "Queen of Air Darkness (The Dark Artifices) Book Three", "author": "Cassandra Clare", "image": "Queen of Air and Darkness- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "Someday - JS Mayank is an Indian author known for his book SomeDay, which explores themes of love, relationships, and self-discovery. The novel follows the journey of two individuals, Abeer and Shreya, who experience the complexities of life, love, and fate. JS Mayank delves into the emotional struggles and joys of the characters, capturing the essence of human connection. His writing reflects his deep understanding of human emotions and interpersonal dynamics. Mayank's storytelling style is both relatable and reflective, appealing to readers who enjoy heartfelt narratives about love and personal growth." ,"id" : "9" , "return_date": "", "title": "Someday", "author": "J S Mayank", "image": "someday- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "Taylor Swift - Evermore - \"Evermore\" is a melancholic and reflective song by Taylor Swift, featuring Bon Iver, from her 2020 album of the same name. The lyrics explore themes of loneliness, despair, and the passage of time, capturing the feeling of being trapped in an endless cycle of sadness. The song begins with Swift describing emotional pain and uncertainty, questioning whether the sorrow will ever fade. As the track progresses, Bon Iver's deep vocals add a sense of longing and desperation, enhancing the song's haunting atmosphere. Toward the end, the lyrics shift to a more hopeful tone, suggesting that healing is possible and that sadness is not eternal. The song's piano-driven melody and orchestral instrumentation create a dreamlike, cinematic effect, making it one of the most powerful and introspective tracks on the album." ,"id" : "10" , "return_date": "", "title": "Taylor Swift - Evermore", "author": "Taylor Swift", "image": "taylor swift evermore- non fiction.jpg", "category": "non-fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2020", "status": "Available"},
        { "synopsis" : "The Old Farmer's 2018 Almanac - \"The Old Farmer's 2018 Almanac\" is a yearly publication filled with weather forecasts, gardening tips, astronomical events, and practical advice for farmers and general readers alike. First published in 1792, the almanac has become a trusted source for long-range weather predictions across North America. The 2018 edition includes seasonal guides for planting, home remedies, folklore, and insights on natural phenomena. It also features articles on topics like climate change, moon phases, cooking recipes, and historical trivia. With a mix of wisdom, humor, and useful information, the almanac remains a popular reference for those interested in nature, agriculture, and self-sufficient living." ,"id" : "11" , "return_date": "", "title": "The Old Farmer's 2018 Almanac", "author": "Robert B. Thomas", "image": "the old farmers 2018 almanac- non fiction.jpg", "category": "non-fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "The Way You Make Me Feel - \"The Way You Make Me Feel\" is a 2018 young adult novel by Maurene Goo that explores themes of self-discovery, friendship, family, and love. The story follows Clara Shin, a prank-loving teenager who doesn't take life too seriously—until one of her pranks goes too far. As punishment, her father forces her to spend the summer working at his Korean-Brazilian food truck alongside her uptight classmate, Rose Carver. At first, Clara and Rose clash, but over time, they develop an unexpected friendship. Meanwhile, Clara meets Hamlet, a sweet and charming boy who challenges her outlook on life. Through her summer experiences, Clara learns about responsibility, personal growth, and the importance of meaningful connections." ,"id" : "12" , "return_date": "", "title": "The Way You Make Me Feel", "author": "Maureen Goo", "image": "the way you make me feel- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "The Wicked King - \"The Wicked King\" is the second book in The Folk of the Air series by Holly Black, published in 2019. The story follows Jude Duarte, a mortal girl who has outmaneuvered the fae and placed Cardan Greenbriar on the throne of Elfhame while secretly controlling him. As she struggles to maintain power, Jude faces betrayal, political intrigue, and threats from enemies who seek to overthrow her. Meanwhile, Cardan grows into his role as king, becoming more unpredictable and dangerous. As tensions rise, Jude must navigate deadly court politics while dealing with her complicated feelings for Cardan. When shocking betrayals come to light, she finds herself outplayed in ways she never expected. The book ends on a devastating cliffhanger, setting the stage for the final installment in the series." ,"id" : "13" , "return_date": "", "title": "The Wicked King", "author": "Holly Black", "image": "the wicked king- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "The World of Harry Potter - \"Harry Potter: A History of Magic\", published in 2018, is a companion book to the British Library's exhibition celebrating 20 years of Harry Potter. It explores the magical traditions, myths, and folklore that inspired J.K. Rowling's beloved series. The book features rare manuscripts, historical artifacts, and unseen sketches from Rowling and illustrator Jim Kay. Readers will discover how real-world alchemy, astronomy, and magical creatures shaped the wizarding world. With contributions from experts and historians, this beautifully illustrated book offers a deeper appreciation of the magic behind the story. It is an essential read for fans eager to explore the real-life roots of the Harry Potter universe." ,"id" : "14" , "return_date": "", "title": "The World of Harry Potter", "author": "J.K. Rowling", "image": "the world of harry potter- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "Unearthed - \"Unearthed\" is a 2018 sci-fi adventure novel by Amie Kaufman and Meagan Spooner, the first book in a duology. The story follows Amelia \"Mia\" Radcliffe, a scavenger trying to survive, and Jules Addison, a scholar seeking knowledge, as they journey to the long-abandoned planet of Gaelea. Gaelea was once home to an advanced alien civilization, the Undying, and is believed to hold secrets that could benefit humanity. While Mia hopes to find valuable artifacts to sell, Jules is determined to decode an ancient message that could change everything. As they navigate deadly traps, solve complex puzzles, and uncover shocking truths, they realize the Undying's warnings might not have been meant to protect the planet, but to protect the universe from what lies within. Their survival becomes a race against time as they learn that Gaelea's mysteries are far more dangerous than they ever imagined." ,"id" : "15" , "return_date": "", "title": "Unearthed", "author": "Amie Kaufman and Meagan Spooner", "image": "Unearthed- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "War Storm - \"War Storm\" is the fourth and final book in the Red Queen series by Victoria Aveyard, published in 2018. The story follows Mare Barrow, a Red-blooded girl with Silver abilities, as she continues her fight against the oppressive Silver elite and their tyrannical rule. After suffering betrayal at the hands of Cal, who chooses his crown over their love, Mare is determined to defeat King Maven, whose obsession with her fuels his dangerous decisions. As alliances shift and war looms, Mare joins forces with the Scarlet Guard, Montfort, and other rebel factions to overthrow the monarchy and establish equality. Meanwhile, Evangeline Samos struggles with her own desires for freedom as political pressures mount. The final battle brings shocking twists, heartbreak, and sacrifices as Mare faces her ultimate enemy—and decides the fate of Norta once and for all." ,"id" : "16" , "return_date": "", "title": "War Storm", "author": "Victoria Aveyard", "image": "war storm- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2019", "status": "Available"},
        { "synopsis" : "Winter of Summers - \"Winter of Summers\" is a 2018 novel by Michael Faudet, known for his poetry and prose. The book is a collection of short stories, poems, and musings that explore themes of love, longing, heartbreak, passion, and nostalgia. With Faudet's signature style of whimsical yet deeply emotional writing, the book delves into the complexities of human relationships, capturing both the beauty and pain of romance. Each piece is crafted to evoke emotion, often blending reality with dreamlike imagery. The book follows no single narrative but instead offers a series of intimate reflections on love and loss, making it a poignant and thought-provoking read." ,"id" : "17" , "return_date": "", "title": "Winter of Summers", "author": "Michael Faudet", "image": "winter of summer- fiction.jpg", "category": "fiction", "type": "Foreign", "shelf" : "Third Shelf", "year": "2018", "status": "Available"},
        { "synopsis" : "Always Be Creating - \"Always Be Creating: A Field Guide to Living a Creative Life\" is a 2018 book by artist and best-selling author Abbey Sy. In this curated collection, she shares personal anecdotes, insightful tips, and life hacks aimed at inspiring artists and creatives. The guide delves into her creative journey, offering readers practical advice on discovering and nurturing their own artistic paths. Whether you're just starting out or already immersed in your creative endeavors, this field guide provides valuable insights to help you live a purposeful, art-enriched life." ,"id" : "18" , "return_date" : "" ,"status" : "Available" , "title": "Always Be Creating", "author": "Abbey Sy", "image": "Always Be Creating.jpg", "category": "Non-fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "History of the Philippines - José Raymund Canoy's \"An Illustrated History of the Philippines\" provides a comprehensive yet accessible overview of Philippine history. It explores key periods, from the pre-colonial era to modern times, with detailed analysis and rich illustrations. The book connects historical events to contemporary issues, offering valuable insights into the nation's development. Canoy's engaging narrative makes history approachable for students, educators, and enthusiasts alike. This book serves as both an informative guide and a visually captivating journey through the Philippines' complex past." ,"id" : "19" , "return_date" : "" ,"status" : "Available" , "title": "History of the Philippines", "author": "Jose Raymund Canoy", "image": "An Illustrated History of the Philippines.jpg", "category": "Non-fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "Are You Called to Go or Called to Say? - \"An Illustrated History of the Philippines\" by José Raymund Canoy is a compelling and visually rich account of the nation's past. The book provides an in-depth exploration of the archipelago's history, from its pre-colonial societies and indigenous cultures to the impact of Spanish colonization, American rule, and Japanese occupation during World War II. It delves into the struggles for independence, highlighting key revolutions, political shifts, and the rise of nationalism. Through detailed narratives and historical illustrations, Canoy presents the economic, social, and political transformations that have shaped modern-day Philippines. This work serves as both an educational resource and an engaging visual journey, making history accessible to readers of all backgrounds." ,"id" : "20" , "return_date" : "" ,"status" : "Available" , "title": "Are You Called to Go or Called to Say?", "author": "Ana Gamez & Lollette Calingasan", "image": "Are You Called To Go or Called To Stay_.jpg", "category": "Non-fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "Balarila ng Wikang Pambansa - Balarila ng Wikang Pambansa is a comprehensive book on Filipino grammar written by Lope K. Santos. It serves as a foundational guide to the proper structure, rules, and usage of the Filipino language. The book covers essential topics such as parts of speech, sentence construction, and proper spelling and punctuation. Originally published in the 1940s, it played a crucial role in standardizing the Filipino language. It remains an important reference for students, educators, and language scholars. Through this work, Lope K. Santos helped shape the formal study of Filipino and its evolution as the national language of the Philippines." ,"id" : "21" , "return_date" : "" ,"status" : "Available" , "title": "Balarila ng Wikang Pambansa", "author": "Lope K. Santos", "image": "Balarila Ng Wikang Pambansa.jpg", "category": "Non-fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2019" },
        { "synopsis" : "Business Finance for Senior High School - Business Finance for Senior High School is a textbook designed to introduce students to fundamental financial concepts in business. It covers essential topics such as financial management, investment decisions, budgeting, and risk management. The book explains how businesses acquire, allocate, and utilize financial resources to achieve growth and stability. It also highlights the importance of financial planning, analyzing financial statements, and making informed business decisions. With practical examples and real-world applications, the book helps students understand the role of finance in entrepreneurship and corporate settings. This resource equips senior high school students with the knowledge needed for future careers in business, accounting, and finance." ,"id" : "22" , "return_date" : "" ,"status" : "Available" , "title": "Business Finance for Senior High School", "author": "Angeles A. Guzman", "image": "Business Finance for Senior High School.jpg", "category": "Non-fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2019" },
        { "synopsis" : "Dish Karte - Dish Karte: Mga Recipe, Diskarte, at Kwentong Pagkain is a cookbook that blends delicious Filipino recipes with inspiring food stories and practical cooking tips. It offers a variety of dishes, from traditional favorites to creative twists, making it perfect for home cooks looking to elevate their skills. The book emphasizes budget-friendly and resourceful cooking, teaching readers how to make the most out of simple ingredients. Alongside recipes, it shares personal anecdotes and insights on Filipino food culture, making it more than just a cookbook. It is written in an engaging and relatable way, encouraging readers to experiment and enjoy the process of cooking. Dish Karte is a must-have for food lovers who want to explore Filipino cuisine with creativity and heart." ,"id" : "23" , "return_date" : "" ,"status" : "Available" , "title": "Dish Karte", "author": "Chef Tatung Sarthou", "image": "Dish Karte.jpg", "category": "Non-fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "El Tiempo Cura Todo - \"El Tiempo Cura Todo\"(translated as \"Time Heals Everything\") is a Spanish-language film or series that explores themes of love, heartbreak, and personal growth. The story typically centers around the emotional journey of the characters as they navigate life's challenges, particularly the healing process after a significant loss or trauma. The phrase \"time heals everything\" suggests a narrative where the characters undergo deep emotional struggles, and over time, they learn to cope, heal, and ultimately move forward." ,"id" : "24" , "return_date" : "" ,"status" : "Available" , "title": "El Tiempo Cura Todo", "author": "Binibining Mia", "image": "El Tiempo Cura Todo.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2019" },
        { "synopsis" : "History with Lourd - History with Lourd is a book by Lourd de Veyra that presents Philippine history in a witty, engaging, and thought-provoking manner. It explores historical events, figures, and issues with a mix of humor, sarcasm, and deep insight, making history more relatable and entertaining. The book challenges traditional narratives, questioning myths and misconceptions while shedding light on lesser-known aspects of the past. Lourd de Veyra's sharp writing style makes history feel alive, relevant, and even controversial at times. Through essays and reflections, he encourages readers to think critically about the past and its impact on the present. History with Lourd is a refreshing take on history that appeals to both history buffs and casual readers." ,"id" : "25" , "return_date" : "" ,"status" : "Available" , "title": "History with Lourd", "author": "Lourd Ernesth H. De Veyra", "image": "History With Lourd.jpg", "category": "Non-fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "I Love You Since 1892 - I Love You Since 1892 is a historical-romance novel by Binibining Mia, originally published on Wattpad before being released in print. The story follows Carmela, a modern-day woman who mysteriously wakes up in the year 1892, during the Spanish colonial era in the Philippines. She meets Juanito, a principled and charming ilustrado, and as she navigates the challenges of the past, she finds herself falling in love with him. However, their love is threatened by societal norms, political tensions, and Carmela's uncertain fate in a time she doesn't belong to. As she struggles to understand her purpose in the past, she is faced with a difficult choice—stay for love or find a way back to her own time. The novel blends romance, history, and mystery, offering a unique take on time-travel and forbidden love." ,"id" : "26" , "return_date" : "" ,"status" : "Available" , "title": "I Love You Since 1892", "author": "Binibining Mia", "image": "I Love You Since 1892.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "I Love You Since 1892 (Ikalawang Bahagi) - The ikalawang bahagi (second part) of I Love You Since 1892 continues Carmela's journey in the past as she becomes more entangled in the events of 1892. As her feelings for Juanito deepen, she also faces increasing dangers, especially with the growing political unrest in the Philippines during the Spanish colonial period. Secrets about her true purpose in the past begin to unravel, making her question whether she was sent there for love or for a greater mission. Meanwhile, new challenges and rivals threaten to separate her and Juanito, testing the strength of their love. Carmela must make crucial decisions that could change both their fates and the course of history. The second book intensifies the romance, drama, and historical intrigue, drawing readers deeper into this time-travel love story." ,"id" : "27" , "return_date" : "" ,"status" : "Available" , "title": "I Love You Since 1892 - Ikalawang Bahagi", "author": "Binibining Mia", "image": "I Love You Since 1892.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "I Love You Since 1892 (Ikatlong bahagi) - The ikatlong bahagi (third part) of I Love You Since 1892 delves deeper into Carmela's struggles as she becomes more involved in the dangerous world of 1892. As the revolution against Spanish rule gains momentum, she realizes that her presence in the past is not just about love, but also about destiny. Her relationship with Juanito faces even greater trials, with betrayals, political conflicts, and the looming possibility that she may have to return to her own time. As secrets from both the past and future unravel, Carmela must decide whether to fight for her love or fulfill a greater mission that could change history. With the weight of both romance and responsibility on her shoulders, she is forced to make a heartbreaking choice. This installment brings more suspense, heartbreak, and revelations, keeping readers hooked on her time-traveling journey." ,"id" : "28" , "return_date" : "" ,"status" : "Available" , "title": "I Love You Since 1892 - Ikatlong Bahagi", "author": "Binibining Mia", "image": "I Love You Since 1892.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2019" },
        { "synopsis" : "I Love You Since 1892 (Ika-apat na bahagi) -  The ikaapat na bahagi (fourth part) of I Love You Since 1892 brings Carmela closer to uncovering the true reason behind her journey to the past. As the revolution against the Spanish intensifies, she faces life-threatening dangers and must choose between staying with Juanito or fulfilling her mission that could alter history. The love between Carmela and Juanito is tested by betrayals, shifting alliances, and the harsh realities of war. Meanwhile, secrets about her connection to the past continue to unfold, making her question if she was ever meant to stay. As time runs out, she must make her most painful decision yet—will she fight for love or return to her own world? This installment is filled with suspense, heartbreak, and a deeper dive into the sacrifices that come with love and destiny." ,"id" : "29" , "return_date" : "" ,"status" : "Available" , "title": "I Love You Since 1892 - Ikaapat na Bahagi", "author": "Binibining Mia", "image": "I Love You Since 1892.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2019" },
        { "synopsis" : "I Love You Since 1892 (Ika-limang bahagi) - The ikalimang bahagi (fifth part) of I Love You Since 1892 intensifies Carmela's struggles as she faces the heartbreaking consequences of her choices. With the Philippine revolution escalating, she is caught between her love for Juanito and her mysterious connection to history. As danger looms closer, she realizes that her presence in 1892 may have far-reaching effects that could alter the future. Secrets from both past and present continue to unravel, forcing Carmela to confront painful truths about her identity and purpose. With fate pushing her toward an inevitable decision, she must determine if love is strong enough to defy time. This installment is filled with emotional turmoil, historical intrigue, and shocking revelations that leave readers eagerly anticipating what comes next." ,"id" : "30" , "return_date" : "" ,"status" : "Available" , "title": "I Love You Since 1892 - Ikalimang Bahagi", "author": "Binibining Mia", "image": "I Love You Since 1892.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2019" },
        { "synopsis" : "Kulto - \"Kulto\" by Gerald Gruezo is a suspenseful novel that follows a protagonist who finds themselves entangled in a mysterious and terrifying cult. As they try to escape its grasp, they uncover dark secrets hidden beneath the surface of what seemed like an ordinary group. The deeper they dig, the more dangerous their situation becomes, as the cult's influence extends far beyond what they imagined. With every turn, paranoia and fear intensify, blurring the lines between reality and illusion. The novel is filled with unexpected twists, psychological tension, and a chilling exploration of manipulation and belief. \"Kulto\" keeps readers on edge as it unravels the terrifying depths of human obsession and control." ,"id" : "31" , "return_date" : "" ,"status" : "Available" , "title": "Kulto", "author": "Gerald Gruezo", "image": "Kulto.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "Librong Itim - \"Librong Itim Volume 4\" is the fourth installment in the anthology series featuring short Philippine horror stories. Published in 2018, this volume continues to showcase eerie tales written by various Filipino authors, blending folklore, superstition, and modern horror. The stories explore a range of supernatural encounters, including cursed objects, haunted locations, and ghostly apparitions. Each tale presents a chilling perspective on fear, drawing from both traditional myths and contemporary nightmares. With a mix of psychological horror and spine-tingling suspense, the collection aims to immerse readers in the dark and mysterious world of Philippine horror. \"Librong Itim Volume 4\" is perfect for those who enjoy unsettling stories that reflect the rich supernatural traditions of the Philippines." ,"id" : "32" , "return_date" : "" ,"status" : "Available" , "title": "Librong Itim", "author": "Maureen Nica B. Lacuata", "image": "Librong Itim.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "Make Love Not War - Make Love Not War\" by Senator Nancy Binay and social media personality Senyora Santibañez is a humorous yet insightful guide on handling online criticism and negativity. Published in 2018, the book shares ten fundamental rules for engaging on social media, emphasizing kindness and avoiding public conflicts. Binay draws from her experiences as a frequent target of online bashing, while Senyora humorously categorizes different types of online adversaries, such as keyboard warriors and frenemies. The book promotes responding to negativity with love and understanding rather than aggression. It also includes a \"happiness checklist\" to help readers assess their well-being and a witty Q&A section. Through humor and practical advice, the book encourages a positive and resilient approach to social media interactions." ,"id" : "33" , "return_date" : "" ,"status" : "Available" , "title": "Make Love Not War", "author": "Nancy Binay, Senyora", "image": "Make Love Not War.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "Minsan Okay Lang Ma-Traffic - \"Minsan Okay Lang Ma-Traffic\" is a short story that explores the frustrations and unexpected lessons of being stuck in traffic. The main character initially feels irritated by the delay, seeing it as a waste of time. However, as they observe their surroundings, they notice small yet meaningful moments—street vendors working hard, strangers sharing conversations, and the quiet beauty of the city. This pause in movement gives them time to reflect on life, relationships, and personal growth. They realize that not all delays are negative; sometimes, they offer a chance to slow down and appreciate the present. The story teaches that just like in life, being \"stuck\" can lead to new perspectives and hidden blessings." ,"id" : "34" , "return_date" : "" ,"status" : "Available" , "title": "Minsan Okay Lang Ma-Traffic", "author": "Charina Clarice Echaluce", "image": "Minsan Okay Lang Ma-Traffic.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "Miss Granny - \"Miss Granny\" is a 2018 Filipino comedy-drama film based on the 2014 South Korean movie of the same name. The story follows Fely, a 70-year-old woman who is outspoken and stubborn, often clashing with her family. Feeling like a burden, she stumbles upon a mysterious photo studio and takes a picture—only to magically transform into her 20-year-old self. Now calling herself Audrey, she gets a second chance at youth, rekindling her dreams of becoming a singer. However, as she enjoys her new life, she faces unexpected challenges, including falling in love and struggling to keep her secret. The film beautifully explores themes of family, self-discovery, and second chances, with heartwarming and comedic moments." ,"id" : "35" , "return_date" : "" ,"status" : "Available" , "title": "Miss Granny", "author": "Rinka Sycip", "image": "Miss Granny.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "Queen of the Universe - \"Queen of the Universe\" is a debut novel by Pia Wurtzbach, the 2015 Miss Universe titleholder. The story centers on Cleo, a young, talented, and beautiful woman striving to make her mark in the competitive world of international beauty pageants. Driven by a desire to prove herself and to show her estranged father—a renowned film director—that she can succeed without his support, Cleo embarks on a journey filled with challenges and self-discovery. As the competition intensifies, she encounters underhanded tactics from fellow contestants, forcing her to question the value of her integrity and the true cost of fame. Set against the vibrant backdrop of Manila's urban life, the novel delves into themes of ambition, personal growth, and the sacrifices one might make in the pursuit of success." ,"id" : "36" , "return_date" : "2025-03-04" ,"status" : "Unavailable" , "title": "Queen of the Universe", "author": "Pia Wurtzbach", "image": "Queen of the Universe.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "Soaring High - \"Soaring High: Your Flight Plan for Your Best Career Ever!\" by Nelson T. Dy is a career development guide that provides practical strategies for professional growth. The book is divided into 30 chapters, each offering insights on topics like job hunting, career advancement, workplace challenges, and planning for retirement. Dy shares personal anecdotes and real-world experiences to help readers navigate the corporate world effectively. He emphasizes the importance of resilience, adaptability, and purpose in achieving career success. The book also provides actionable tips, making it a valuable resource for both young professionals and seasoned employees. Ultimately, \"Soaring High\" serves as a roadmap for those seeking fulfillment and excellence in their careers." ,"id" : "37" , "return_date" : "" ,"status" : "Available" , "title": "Soaring High", "author": "Nelson Dy", "image": "Soaring High.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "Su Punto de Vista -  \"Su Punto de Vista\" by Binibining Mia is a companion novel to I Love You Since 1892, told from the perspective of Juanito Alfonso, the male protagonist. This book offers a deeper insight into Juanito's thoughts, emotions, and struggles as he navigates love, family expectations, and the challenges of his time. Through his point of view, readers gain a fresh understanding of his motivations and his relationship with Carmela. The novel adds depth to the original story, showcasing his internal conflicts and decisions that shape their fate. With a poetic and heartfelt narrative, \"Su Punto de Vista\" provides a richer experience of the historical rom" ,"id" : "38" , "return_date" : "2025-03-07" ,"status" : "Unavailable" , "title": "Su Punto de Vista", "author": "Binibining Mia", "image": "Su Punto De Vista.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2019" },
        { "synopsis" : "The Education Act - \"The Education Act\" by Joseph Noel M. Estrada is a comprehensive guide to Philippine education law, policies, and regulations. It compiles statutes, jurisprudence, and administrative orders that shape the country's educational system. The book covers key topics such as governance, academic standards, teachers' rights, student welfare, and institutional policies. It serves as a valuable resource for educators, policymakers, and legal professionals seeking clarity on education-related legal matters. By analyzing existing laws and policies, it helps readers understand their implications on schools and learners. Ultimately, the book aims to support informed decision-making and effective educational reforms in the Philippines." ,"id" : "39" , "return_date" : "" ,"status" : "Available" , "title": "The Education Act", "author": "Joseph Noel M. Estrada", "image": "The Education Act.png", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" },
        { "synopsis" : "The Hows of Us - The Hows of Us (2018) is a Filipino romantic drama film directed by Cathy Garcia-Molina, starring Kathryn Bernardo and Daniel Padilla. The movie follows Primo (Daniel Padilla) and George (Kathryn Bernardo), a young couple who have been together for years, dreaming of a future together. George is a hardworking medical student, while Primo is an aspiring musician struggling to find success.As time passes, their once-sweet relationship is tested by personal ambitions, financial struggles, and conflicting priorities. Primo's relentless pursuit of his dreams causes friction, leaving George to question whether their love is still worth fighting for. Eventually, Primo leaves, and George is left to pick up the pieces of her life." ,"id" : "40" , "return_date" : "2025-03-21" ,"status" : "Unavailable" , "title": "The Hows of Us", "author": "Charmain Lasar", "image": "The Hows Of Us.jpg", "category": "Fiction", "type": "Filipiniana", "shelf" : "Second Shelf", "year": "2018" }
    ];
    
    function displayBooks(filteredBooks = books) {
        const container = document.getElementById('bookContainer');
        container.innerHTML = '';
        filteredBooks.forEach((book) => {
            const bookCard = document.createElement("div");
            bookCard.className = "col-md-4 mb-3";
            bookCard.innerHTML = `
                <div class="card book-card" data-index="${book.id}">
                    <img src="${book.image}" class="card-img-top" alt="${book.title}">
                    <div class="card-body">
                        <h5 class="card-title">${book.title}</h5>
                        <p class="card-text"><strong>Author:</strong> ${book.author}</p>
                        <p class="card-text"><strong>Category:</strong> ${book.category}</p>
                        <p class="card-text"><strong>Type:</strong> ${book.type}</p>
                        <p class="card-text"><strong>Year:</strong> ${book.year}</p>
                        <p class="card-text"><strong>Shelf:</strong> ${book.shelf}</p>
                        <p class="card-text"><strong>Status:</strong> ${book.status}</p>
                        <p class="card-text"><strong>Return Date:</strong> ${book.return_date}</p>
                    </div>
                </div>
            `;
            container.appendChild(bookCard);
    
            // Add click event to open modal
            bookCard.addEventListener("click", function () {
                openBookModal(book.id);
            });
        });
    }
    
    function openBookModal(book_id) {
        const book = books.find(book => book.id === book_id);
        document.getElementById("bookTitle").innerText = book.title;
        document.getElementById("bookImage").src = book.image;
        document.getElementById('bookSummary').textContent = book.synopsis;
        const bookModal = new bootstrap.Modal(document.getElementById("bookModal"));
        bookModal.show();
    }
    
    window.searchBooks = function() {
        const searchValue = document.getElementById('searchInput').value.toLowerCase();
        const filteredBooks = books.filter(book =>
            book.title.toLowerCase().includes(searchValue) ||
            book.author.toLowerCase().includes(searchValue) ||
            book.category.toLowerCase().includes(searchValue) ||
            book.type.toLowerCase().includes(searchValue) ||
            book.shelf.toLowerCase().includes(searchValue) ||
            book.year.toLowerCase().includes(searchValue) ||
            book.status.toLowerCase().includes(searchValue)
        );
        displayBooks(filteredBooks);
    };

    window.sortBooks = function() {
        const sortBy = document.getElementById('sortSelect').value;
        const sortedBooks = [...books].sort((a, b) => a[sortBy].localeCompare(b[sortBy]));
        displayBooks(sortedBooks);
    };

    // Add event listeners instead of using inline event handlers
    document.getElementById("searchInput").addEventListener("keyup", searchBooks);
    document.getElementById("sortSelect").addEventListener("change", sortBooks);
    
    // Display books on page load
    displayBooks();
});

function logout() {
    alert("You have been logged out.");
    // Add your logout logic here (e.g., clearing session storage, redirecting to login page)
    window.location.href = "index.html"; // Redirect to login page
}